/* Copyright 2026 Google Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package gonids

import (
	"bufio"
	"fmt"
	"io"
	"strings"
)

// RuleScanner provides a convenient interface for reading IDS rules sequentially from an io.Reader.
// It transparently handles multi-line rules ending with backslash (\), blank lines, and comments.
type RuleScanner struct {
	reader          *bufio.Reader
	currRule        *Rule
	currRaw         string
	currLine        int
	startLine       int
	err             error
	eof             bool
	IncludeComments bool
}

// NewRuleScanner returns a new RuleScanner to read from r.
func NewRuleScanner(r io.Reader) *RuleScanner {
	return &RuleScanner{
		reader: bufio.NewReader(r),
	}
}

// isRuleCandidate checks if a line looks like an active or disabled IDS rule.
func isRuleCandidate(line string) bool {
	t := strings.TrimSpace(line)
	if t == "" {
		return false
	}
	trimmed := strings.TrimLeft(t, "# \t")
	fields := strings.Fields(trimmed)
	if len(fields) < 2 {
		return false
	}
	action := strings.ToLower(fields[0])
	if !inSlice(action, []string{"alert", "drop", "pass", "reject", "sdrop", "log"}) {
		return false
	}
	protocol := strings.ToLower(fields[1])
	return inSlice(protocol, appLayerProtocols)
}

// Scan advances the scanner to the next rule in the input stream.
// It returns false when the scan stops, either by reaching the end of the input or encountering an error.
func (s *RuleScanner) Scan() bool {
	if s.eof || s.err != nil {
		return false
	}

	for {
		line, err := s.reader.ReadString('\n')
		if len(line) > 0 {
			s.currLine++
		}
		if err != nil {
			if err == io.EOF {
				s.eof = true
				if len(line) == 0 {
					return false
				}
			} else {
				s.err = fmt.Errorf("read error at line %d: %w", s.currLine, err)
				return false
			}
		}

		cleanLine := strings.TrimRight(line, "\r\n")
		trimmedEnd := strings.TrimRight(cleanLine, " \t")
		hasContinuation := strings.HasSuffix(trimmedEnd, "\\")
		if hasContinuation {
			cleanLine = strings.TrimSuffix(trimmedEnd, "\\")
		}
		trimmed := strings.TrimSpace(cleanLine)

		if trimmed == "" {
			if s.IncludeComments {
				s.currRule = nil
				s.currRaw = ""
				s.startLine = s.currLine
				return true
			}
			continue
		}

		if !isRuleCandidate(trimmed) {
			if s.IncludeComments {
				s.currRule = nil
				s.currRaw = cleanLine
				s.startLine = s.currLine
				return true
			}
			continue
		}

		var combined strings.Builder
		ruleStartLine := s.currLine
		combined.WriteString(trimmed)

		for hasContinuation && !s.eof {
			line, err := s.reader.ReadString('\n')
			if len(line) > 0 {
				s.currLine++
			}
			if err != nil {
				if err == io.EOF {
					s.eof = true
				} else {
					s.err = fmt.Errorf("read error at line %d: %w", s.currLine, err)
					return false
				}
			}
			cleanContLine := strings.TrimRight(line, "\r\n")
			trimmedContEnd := strings.TrimRight(cleanContLine, " \t")
			hasContinuation = strings.HasSuffix(trimmedContEnd, "\\")
			if hasContinuation {
				cleanContLine = strings.TrimSuffix(trimmedContEnd, "\\")
			}
			continuationLine := strings.TrimSpace(cleanContLine)
			if strings.HasPrefix(continuationLine, "#") {
				continuationLine = strings.TrimLeft(continuationLine, "# \t")
			}
			if continuationLine != "" {
				combined.WriteString(" ")
				combined.WriteString(continuationLine)
			}
		}

		raw := combined.String()
		rule, err := ParseRule(raw)
		if err != nil {
			s.err = fmt.Errorf("line %d: %w", ruleStartLine, err)
			return false
		}

		s.currRule = rule
		s.currRaw = raw
		s.startLine = ruleStartLine
		return true
	}
}

// Rule returns the most recent rule generated by a call to Scan.
func (s *RuleScanner) Rule() *Rule {
	return s.currRule
}

// Raw returns the unparsed raw rule string for the most recent rule.
func (s *RuleScanner) Raw() string {
	return s.currRaw
}

// LineNumber returns the starting line number of the most recent rule.
func (s *RuleScanner) LineNumber() int {
	return s.startLine
}

// Err returns the first non-EOF error that was encountered by the scanner.
func (s *RuleScanner) Err() error {
	return s.err
}
